services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/timer/app
    depends_on:
      - mysql
  mysql:
    image: mysql:lts
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 3
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
